# Generated by Django 4.2 on 2023-05-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstorage',
            name='not_finish',
            field=models.BooleanField(default=False, verbose_name='Письмо'),
        ),
    ]
