# Generated by Django 4.2 on 2023-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callapplication',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='callapplication',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callapplication',
            name='topic',
            field=models.CharField(default=0, max_length=50, verbose_name='Тема обращения'),
            preserve_default=False,
        ),
    ]
