# Generated by Django 4.2 on 2023-05-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderstorage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresssirvice',
            name='placehold',
        ),
        migrations.DeleteModel(
            name='PlaceHold',
        ),
    ]
